### ISSUE TITLE
Export blender lights

### ISSUE THREAD

**Issue by silverslade** [silverslade/aframe_blender_exporter#12]
The actual version of the add-on doesn't yet export blender lights in scene (it exports only 3D Meshes). Add an option to export the lights too (letting the user choose if export the lights or use the 2 default lights)

**Comment by s-light** [comment]
as fare as i have seen in the current code this is fixed now?!

**Comment by s-light** [comment]
just tested: 
for me it works in blender 3.1.0 with #17
