### ISSUE TITLE
crashes dos not work

### ISSUE THREAD

**Issue by kordou** [silverslade/aframe_blender_exporter#21]
hi i just boght the plugin bu it dos not work

Python: Traceback (most recent call last):
  File "C:\Users\ko-ph\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\aframe_blender_exporter_0_0_8\__init__.py", line 592, in execute
    bpy.ops.export_scene.gltf(filepath=filename, export_format='GLTF_EMBEDDED', use_selection=True, export_texcoords = True, export_normals = True, export_draco_mesh_compression_enable = False, export_draco_mesh_compression_level = 6, export_draco_position_quantization = 14, export_draco_normal_quantization = 10, export_draco_texcoord_quantization = 12, export_draco_generic_quantization = 12,export_tangents = True, export_materials = 'EXPORT', export_colors = True, export_extras = True, export_yup = True, export_apply = True, export_animations = True, export_frame_range = True, export_frame_step = 1, export_force_sampling = True, export_displacement = True)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "export_displacement" unrecognized

**Comment by silverslade** [comment]
Hi Kordou
the actual version of aframe exporter doesn't support Blender 3.4 yet.
Try with blender 3.0

**Comment by silverslade** [comment]
Hi Kordou
just released the 0.0.9 version: this version runs fine on Blender 3.5.1
Check out it
