### ISSUE TITLE
Trying to export using 3.5.1

### ISSUE THREAD

**Issue by octu8re** [silverslade/aframe_blender_exporter#22]
Hello there!
I'm getting this every time:

Python: Traceback (most recent call last):
  File "C:\Users\***\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\aframe_blender_exporter-master\__init__.py", line 565, in execute
    shutil.copyfile ( os.path.join ( SRC_RES, fname ), os.path.join ( DEST_RES, dest_path, fname ) )
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\***\\AppData\\Roaming\\Blender Foundation\\Blender\\3.5\\scripts\\addons\\aframe_blender_exporter-master\\resources/start_server.bat'

---

Thank you so much. I want to support this.

**Comment by silverslade** [comment]
Hi octu8re
I suspect some anti virus could stop the "start_server.bat" file I added as shortcut to run locally a python web server outside Blender.
I'll remove it in the next release.
Can you confirm other than the error, is the add-on working properly?

**Comment by octu8re** [comment]
Hey silverslade
Based on the video, installation was successfull. The panel looks updated and I can set it up as demonstrated. 
When clicking 'export a-frame project' it popsup the error and then the word 'exporting...' is displayed in the pannel although nothing happens.
That's all I can tell. :(
I believe Serving does as it says. Thank you.

**Comment by silverslade** [comment]
Hi octu8re,
in the 0.0.10 version just removed the bat file and added a python script to start a local web server (for test or delivery the final webxr application).
Check out the 0.0.10 version and let me know.

**Comment by octu8re** [comment]
Tested and got my first export. This is really cool, man!
